version: "3.5"
services:
  front-dev:
    container_name: front
    build: .
    depends_on:
      - "comments"
      - "users"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 1
      DISABLE_ESLINT_PLUGIN: 1
      NODE_ENV: "development"

  comments:
    container_name: comments
    build:
      context: ./api-server-comments
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./api-server-comments:/app
      - /app/node_modules
    restart: always

  users:
    container_name: users
    build:
      context: ./api-server-users
      dockerfile: Dockerfile
    ports:
      - "3002:3001"
    volumes:
      - ./api-server-users:/app
      - /app/node_modules
    restart: always
